// ignore_for_file: camel_case_types
// ignore_for_file: prefer_double_quotes
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: constant_identifier_names
// ignore_for_file: prefer_expression_function_bodies
// ignore_for_file: sort_constructors_first
// ignore_for_file: unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for minisound.h
class MinisoundFfiBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  MinisoundFfiBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  MinisoundFfiBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  ffi.Pointer<EncodedSoundData> encoded_sound_data_alloc() {
    return _encoded_sound_data_alloc();
  }

  late final _encoded_sound_data_allocPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<EncodedSoundData> Function()>>(
          'encoded_sound_data_alloc');
  late final _encoded_sound_data_alloc = _encoded_sound_data_allocPtr
      .asFunction<ffi.Pointer<EncodedSoundData> Function()>();

  Result encoded_sound_data_init(
    ffi.Pointer<EncodedSoundData> self,
    ffi.Pointer<ffi.Uint8> data,
    int data_size,
  ) {
    return Result.fromValue(_encoded_sound_data_init(
      self,
      data,
      data_size,
    ));
  }

  late final _encoded_sound_data_initPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<EncodedSoundData>,
              ffi.Pointer<ffi.Uint8>, ffi.Size)>>('encoded_sound_data_init');
  late final _encoded_sound_data_init = _encoded_sound_data_initPtr.asFunction<
      int Function(
          ffi.Pointer<EncodedSoundData>, ffi.Pointer<ffi.Uint8>, int)>();

  void encoded_sound_data_uninit(
    ffi.Pointer<EncodedSoundData> self,
  ) {
    return _encoded_sound_data_uninit(
      self,
    );
  }

  late final _encoded_sound_data_uninitPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<EncodedSoundData>)>>(
      'encoded_sound_data_uninit');
  late final _encoded_sound_data_uninit = _encoded_sound_data_uninitPtr
      .asFunction<void Function(ffi.Pointer<EncodedSoundData>)>();

  bool encoded_sound_data_get_is_looped(
    ffi.Pointer<EncodedSoundData> self,
  ) {
    return _encoded_sound_data_get_is_looped(
      self,
    );
  }

  late final _encoded_sound_data_get_is_loopedPtr = _lookup<
          ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<EncodedSoundData>)>>(
      'encoded_sound_data_get_is_looped');
  late final _encoded_sound_data_get_is_looped =
      _encoded_sound_data_get_is_loopedPtr
          .asFunction<bool Function(ffi.Pointer<EncodedSoundData>)>();

  void encoded_sound_data_set_looped(
    ffi.Pointer<EncodedSoundData> self,
    bool value,
    int delay_ms,
  ) {
    return _encoded_sound_data_set_looped(
      self,
      value,
      delay_ms,
    );
  }

  late final _encoded_sound_data_set_loopedPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<EncodedSoundData>, ffi.Bool,
              ffi.Size)>>('encoded_sound_data_set_looped');
  late final _encoded_sound_data_set_looped = _encoded_sound_data_set_loopedPtr
      .asFunction<void Function(ffi.Pointer<EncodedSoundData>, bool, int)>();

  SoundData encoded_sound_data_ww_sound_data(
    ffi.Pointer<EncodedSoundData> self,
  ) {
    return _encoded_sound_data_ww_sound_data(
      self,
    );
  }

  late final _encoded_sound_data_ww_sound_dataPtr = _lookup<
          ffi
          .NativeFunction<SoundData Function(ffi.Pointer<EncodedSoundData>)>>(
      'encoded_sound_data_ww_sound_data');
  late final _encoded_sound_data_ww_sound_data =
      _encoded_sound_data_ww_sound_dataPtr
          .asFunction<SoundData Function(ffi.Pointer<EncodedSoundData>)>();

  ffi.Pointer<NoiseSoundData> noise_sound_data_alloc() {
    return _noise_sound_data_alloc();
  }

  late final _noise_sound_data_allocPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<NoiseSoundData> Function()>>(
          'noise_sound_data_alloc');
  late final _noise_sound_data_alloc = _noise_sound_data_allocPtr
      .asFunction<ffi.Pointer<NoiseSoundData> Function()>();

  Result noise_sound_data_init(
    ffi.Pointer<NoiseSoundData> self,
    NoiseType type,
    int format,
    int channels,
  ) {
    return Result.fromValue(_noise_sound_data_init(
      self,
      type.value,
      format,
      channels,
    ));
  }

  late final _noise_sound_data_initPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<NoiseSoundData>, ffi.UnsignedInt,
              ffi.Int, ffi.Uint32)>>('noise_sound_data_init');
  late final _noise_sound_data_init = _noise_sound_data_initPtr
      .asFunction<int Function(ffi.Pointer<NoiseSoundData>, int, int, int)>();

  void noise_sound_data_uninit(
    ffi.Pointer<NoiseSoundData> self,
  ) {
    return _noise_sound_data_uninit(
      self,
    );
  }

  late final _noise_sound_data_uninitPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<NoiseSoundData>)>>(
      'noise_sound_data_uninit');
  late final _noise_sound_data_uninit = _noise_sound_data_uninitPtr
      .asFunction<void Function(ffi.Pointer<NoiseSoundData>)>();

  SoundData noise_sound_data_ww_sound_data(
    ffi.Pointer<NoiseSoundData> self,
  ) {
    return _noise_sound_data_ww_sound_data(
      self,
    );
  }

  late final _noise_sound_data_ww_sound_dataPtr = _lookup<
          ffi.NativeFunction<SoundData Function(ffi.Pointer<NoiseSoundData>)>>(
      'noise_sound_data_ww_sound_data');
  late final _noise_sound_data_ww_sound_data =
      _noise_sound_data_ww_sound_dataPtr
          .asFunction<SoundData Function(ffi.Pointer<NoiseSoundData>)>();

  ffi.Pointer<PulseSoundData> pulse_sound_data_alloc() {
    return _pulse_sound_data_alloc();
  }

  late final _pulse_sound_data_allocPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<PulseSoundData> Function()>>(
          'pulse_sound_data_alloc');
  late final _pulse_sound_data_alloc = _pulse_sound_data_allocPtr
      .asFunction<ffi.Pointer<PulseSoundData> Function()>();

  Result pulse_sound_data_init(
    ffi.Pointer<PulseSoundData> self,
  ) {
    return Result.fromValue(_pulse_sound_data_init(
      self,
    ));
  }

  late final _pulse_sound_data_initPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<PulseSoundData>)>>('pulse_sound_data_init');
  late final _pulse_sound_data_init = _pulse_sound_data_initPtr
      .asFunction<int Function(ffi.Pointer<PulseSoundData>)>();

  void pulse_sound_data_uninit(
    ffi.Pointer<PulseSoundData> self,
  ) {
    return _pulse_sound_data_uninit(
      self,
    );
  }

  late final _pulse_sound_data_uninitPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<PulseSoundData>)>>(
      'pulse_sound_data_uninit');
  late final _pulse_sound_data_uninit = _pulse_sound_data_uninitPtr
      .asFunction<void Function(ffi.Pointer<PulseSoundData>)>();

  double pulse_sound_data_get_freq(
    ffi.Pointer<PulseSoundData> self,
  ) {
    return _pulse_sound_data_get_freq(
      self,
    );
  }

  late final _pulse_sound_data_get_freqPtr = _lookup<
          ffi.NativeFunction<ffi.Double Function(ffi.Pointer<PulseSoundData>)>>(
      'pulse_sound_data_get_freq');
  late final _pulse_sound_data_get_freq = _pulse_sound_data_get_freqPtr
      .asFunction<double Function(ffi.Pointer<PulseSoundData>)>();

  void pulse_sound_data_set_freq(
    ffi.Pointer<PulseSoundData> self,
    double value,
  ) {
    return _pulse_sound_data_set_freq(
      self,
      value,
    );
  }

  late final _pulse_sound_data_set_freqPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<PulseSoundData>,
              ffi.Double)>>('pulse_sound_data_set_freq');
  late final _pulse_sound_data_set_freq = _pulse_sound_data_set_freqPtr
      .asFunction<void Function(ffi.Pointer<PulseSoundData>, double)>();

  double pulse_sound_data_get_duty_cycle(
    ffi.Pointer<PulseSoundData> self,
  ) {
    return _pulse_sound_data_get_duty_cycle(
      self,
    );
  }

  late final _pulse_sound_data_get_duty_cyclePtr = _lookup<
          ffi.NativeFunction<ffi.Double Function(ffi.Pointer<PulseSoundData>)>>(
      'pulse_sound_data_get_duty_cycle');
  late final _pulse_sound_data_get_duty_cycle =
      _pulse_sound_data_get_duty_cyclePtr
          .asFunction<double Function(ffi.Pointer<PulseSoundData>)>();

  void pulse_sound_data_set_duty_cycle(
    ffi.Pointer<PulseSoundData> self,
    double value,
  ) {
    return _pulse_sound_data_set_duty_cycle(
      self,
      value,
    );
  }

  late final _pulse_sound_data_set_duty_cyclePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<PulseSoundData>,
              ffi.Double)>>('pulse_sound_data_set_duty_cycle');
  late final _pulse_sound_data_set_duty_cycle =
      _pulse_sound_data_set_duty_cyclePtr
          .asFunction<void Function(ffi.Pointer<PulseSoundData>, double)>();

  SoundData pulse_sound_data_ww_sound_data(
    ffi.Pointer<PulseSoundData> self,
  ) {
    return _pulse_sound_data_ww_sound_data(
      self,
    );
  }

  late final _pulse_sound_data_ww_sound_dataPtr = _lookup<
          ffi.NativeFunction<SoundData Function(ffi.Pointer<PulseSoundData>)>>(
      'pulse_sound_data_ww_sound_data');
  late final _pulse_sound_data_ww_sound_data =
      _pulse_sound_data_ww_sound_dataPtr
          .asFunction<SoundData Function(ffi.Pointer<PulseSoundData>)>();

  ffi.Pointer<WaveformSoundData> waveform_sound_data_alloc() {
    return _waveform_sound_data_alloc();
  }

  late final _waveform_sound_data_allocPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<WaveformSoundData> Function()>>(
          'waveform_sound_data_alloc');
  late final _waveform_sound_data_alloc = _waveform_sound_data_allocPtr
      .asFunction<ffi.Pointer<WaveformSoundData> Function()>();

  Result waveform_sound_data_init(
    ffi.Pointer<WaveformSoundData> self,
    int format,
    int channels,
    int sample_rate,
  ) {
    return Result.fromValue(_waveform_sound_data_init(
      self,
      format,
      channels,
      sample_rate,
    ));
  }

  late final _waveform_sound_data_initPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<WaveformSoundData>, ffi.Int,
              ffi.Uint32, ffi.Uint32)>>('waveform_sound_data_init');
  late final _waveform_sound_data_init =
      _waveform_sound_data_initPtr.asFunction<
          int Function(ffi.Pointer<WaveformSoundData>, int, int, int)>();

  void waveform_sound_data_uninit(
    ffi.Pointer<WaveformSoundData> self,
  ) {
    return _waveform_sound_data_uninit(
      self,
    );
  }

  late final _waveform_sound_data_uninitPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<WaveformSoundData>)>>(
      'waveform_sound_data_uninit');
  late final _waveform_sound_data_uninit = _waveform_sound_data_uninitPtr
      .asFunction<void Function(ffi.Pointer<WaveformSoundData>)>();

  WaveformType waveform_sound_data_get_type(
    ffi.Pointer<WaveformSoundData> self,
  ) {
    return WaveformType.fromValue(_waveform_sound_data_get_type(
      self,
    ));
  }

  late final _waveform_sound_data_get_typePtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<WaveformSoundData>)>>('waveform_sound_data_get_type');
  late final _waveform_sound_data_get_type = _waveform_sound_data_get_typePtr
      .asFunction<int Function(ffi.Pointer<WaveformSoundData>)>();

  void waveform_sound_data_set_type(
    ffi.Pointer<WaveformSoundData> self,
    WaveformType value,
  ) {
    return _waveform_sound_data_set_type(
      self,
      value.value,
    );
  }

  late final _waveform_sound_data_set_typePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<WaveformSoundData>,
              ffi.UnsignedInt)>>('waveform_sound_data_set_type');
  late final _waveform_sound_data_set_type = _waveform_sound_data_set_typePtr
      .asFunction<void Function(ffi.Pointer<WaveformSoundData>, int)>();

  double waveform_sound_data_get_freq(
    ffi.Pointer<WaveformSoundData> self,
  ) {
    return _waveform_sound_data_get_freq(
      self,
    );
  }

  late final _waveform_sound_data_get_freqPtr = _lookup<
          ffi
          .NativeFunction<ffi.Double Function(ffi.Pointer<WaveformSoundData>)>>(
      'waveform_sound_data_get_freq');
  late final _waveform_sound_data_get_freq = _waveform_sound_data_get_freqPtr
      .asFunction<double Function(ffi.Pointer<WaveformSoundData>)>();

  void waveform_sound_data_set_freq(
    ffi.Pointer<WaveformSoundData> self,
    double value,
  ) {
    return _waveform_sound_data_set_freq(
      self,
      value,
    );
  }

  late final _waveform_sound_data_set_freqPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<WaveformSoundData>,
              ffi.Double)>>('waveform_sound_data_set_freq');
  late final _waveform_sound_data_set_freq = _waveform_sound_data_set_freqPtr
      .asFunction<void Function(ffi.Pointer<WaveformSoundData>, double)>();

  SoundData waveform_sound_data_ww_sound_data(
    ffi.Pointer<WaveformSoundData> self,
  ) {
    return _waveform_sound_data_ww_sound_data(
      self,
    );
  }

  late final _waveform_sound_data_ww_sound_dataPtr = _lookup<
          ffi
          .NativeFunction<SoundData Function(ffi.Pointer<WaveformSoundData>)>>(
      'waveform_sound_data_ww_sound_data');
  late final _waveform_sound_data_ww_sound_data =
      _waveform_sound_data_ww_sound_dataPtr
          .asFunction<SoundData Function(ffi.Pointer<WaveformSoundData>)>();

  ffi.Pointer<Sound> sound_alloc() {
    return _sound_alloc();
  }

  late final _sound_allocPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<Sound> Function()>>('sound_alloc');
  late final _sound_alloc =
      _sound_allocPtr.asFunction<ffi.Pointer<Sound> Function()>();

  Result sound_init(
    ffi.Pointer<Sound> self,
    SoundData sound_data,
    ffi.Pointer<ma_engine> engine,
  ) {
    return Result.fromValue(_sound_init(
      self,
      sound_data,
      engine,
    ));
  }

  late final _sound_initPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<Sound>, SoundData,
              ffi.Pointer<ma_engine>)>>('sound_init');
  late final _sound_init = _sound_initPtr.asFunction<
      int Function(ffi.Pointer<Sound>, SoundData, ffi.Pointer<ma_engine>)>();

  void sound_unload(
    ffi.Pointer<Sound> self,
  ) {
    return _sound_unload(
      self,
    );
  }

  late final _sound_unloadPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<Sound>)>>(
          'sound_unload');
  late final _sound_unload =
      _sound_unloadPtr.asFunction<void Function(ffi.Pointer<Sound>)>();

  Result sound_play(
    ffi.Pointer<Sound> self,
  ) {
    return Result.fromValue(_sound_play(
      self,
    ));
  }

  late final _sound_playPtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<Sound>)>>(
          'sound_play');
  late final _sound_play =
      _sound_playPtr.asFunction<int Function(ffi.Pointer<Sound>)>();

  void sound_pause(
    ffi.Pointer<Sound> self,
  ) {
    return _sound_pause(
      self,
    );
  }

  late final _sound_pausePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<Sound>)>>(
          'sound_pause');
  late final _sound_pause =
      _sound_pausePtr.asFunction<void Function(ffi.Pointer<Sound>)>();

  void sound_stop(
    ffi.Pointer<Sound> self,
  ) {
    return _sound_stop(
      self,
    );
  }

  late final _sound_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<Sound>)>>(
          'sound_stop');
  late final _sound_stop =
      _sound_stopPtr.asFunction<void Function(ffi.Pointer<Sound>)>();

  double sound_get_volume(
    ffi.Pointer<Sound> self,
  ) {
    return _sound_get_volume(
      self,
    );
  }

  late final _sound_get_volumePtr =
      _lookup<ffi.NativeFunction<ffi.Float Function(ffi.Pointer<Sound>)>>(
          'sound_get_volume');
  late final _sound_get_volume =
      _sound_get_volumePtr.asFunction<double Function(ffi.Pointer<Sound>)>();

  void sound_set_volume(
    ffi.Pointer<Sound> self,
    double value,
  ) {
    return _sound_set_volume(
      self,
      value,
    );
  }

  late final _sound_set_volumePtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<Sound>, ffi.Float)>>(
      'sound_set_volume');
  late final _sound_set_volume = _sound_set_volumePtr
      .asFunction<void Function(ffi.Pointer<Sound>, double)>();

  double sound_get_duration(
    ffi.Pointer<Sound> self,
  ) {
    return _sound_get_duration(
      self,
    );
  }

  late final _sound_get_durationPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function(ffi.Pointer<Sound>)>>(
          'sound_get_duration');
  late final _sound_get_duration =
      _sound_get_durationPtr.asFunction<double Function(ffi.Pointer<Sound>)>();

  bool sound_get_is_playing(
    ffi.Pointer<Sound> self,
  ) {
    return _sound_get_is_playing(
      self,
    );
  }

  late final _sound_get_is_playingPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<Sound>)>>(
          'sound_get_is_playing');
  late final _sound_get_is_playing =
      _sound_get_is_playingPtr.asFunction<bool Function(ffi.Pointer<Sound>)>();

  double sound_get_cursor(
    ffi.Pointer<Sound> self,
  ) {
    return _sound_get_cursor(
      self,
    );
  }

  late final _sound_get_cursorPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function(ffi.Pointer<Sound>)>>(
          'sound_get_cursor');
  late final _sound_get_cursor =
      _sound_get_cursorPtr.asFunction<double Function(ffi.Pointer<Sound>)>();

  void sound_set_cursor(
    ffi.Pointer<Sound> self,
    double value,
  ) {
    return _sound_set_cursor(
      self,
      value,
    );
  }

  late final _sound_set_cursorPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<Sound>, ffi.Float)>>(
      'sound_set_cursor');
  late final _sound_set_cursor = _sound_set_cursorPtr
      .asFunction<void Function(ffi.Pointer<Sound>, double)>();

  double sound_get_pitch(
    ffi.Pointer<Sound> self,
  ) {
    return _sound_get_pitch(
      self,
    );
  }

  late final _sound_get_pitchPtr =
      _lookup<ffi.NativeFunction<ffi.Float Function(ffi.Pointer<Sound>)>>(
          'sound_get_pitch');
  late final _sound_get_pitch =
      _sound_get_pitchPtr.asFunction<double Function(ffi.Pointer<Sound>)>();

  void sound_set_pitch(
    ffi.Pointer<Sound> self,
    double value,
  ) {
    return _sound_set_pitch(
      self,
      value,
    );
  }

  late final _sound_set_pitchPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<Sound>, ffi.Float)>>(
      'sound_set_pitch');
  late final _sound_set_pitch = _sound_set_pitchPtr
      .asFunction<void Function(ffi.Pointer<Sound>, double)>();

  ffi.Pointer<EncodedSoundData> sound_get_encoded_data(
    ffi.Pointer<Sound> self,
  ) {
    return _sound_get_encoded_data(
      self,
    );
  }

  late final _sound_get_encoded_dataPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<EncodedSoundData> Function(
              ffi.Pointer<Sound>)>>('sound_get_encoded_data');
  late final _sound_get_encoded_data = _sound_get_encoded_dataPtr
      .asFunction<ffi.Pointer<EncodedSoundData> Function(ffi.Pointer<Sound>)>();

  ffi.Pointer<WaveformSoundData> sound_get_waveform_data(
    ffi.Pointer<Sound> self,
  ) {
    return _sound_get_waveform_data(
      self,
    );
  }

  late final _sound_get_waveform_dataPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<WaveformSoundData> Function(
              ffi.Pointer<Sound>)>>('sound_get_waveform_data');
  late final _sound_get_waveform_data = _sound_get_waveform_dataPtr.asFunction<
      ffi.Pointer<WaveformSoundData> Function(ffi.Pointer<Sound>)>();

  ffi.Pointer<NoiseSoundData> sound_get_noise_data(
    ffi.Pointer<Sound> self,
  ) {
    return _sound_get_noise_data(
      self,
    );
  }

  late final _sound_get_noise_dataPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<NoiseSoundData> Function(
              ffi.Pointer<Sound>)>>('sound_get_noise_data');
  late final _sound_get_noise_data = _sound_get_noise_dataPtr
      .asFunction<ffi.Pointer<NoiseSoundData> Function(ffi.Pointer<Sound>)>();

  ffi.Pointer<PulseSoundData> sound_get_pulse_data(
    ffi.Pointer<Sound> self,
  ) {
    return _sound_get_pulse_data(
      self,
    );
  }

  late final _sound_get_pulse_dataPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<PulseSoundData> Function(
              ffi.Pointer<Sound>)>>('sound_get_pulse_data');
  late final _sound_get_pulse_data = _sound_get_pulse_dataPtr
      .asFunction<ffi.Pointer<PulseSoundData> Function(ffi.Pointer<Sound>)>();

  ffi.Pointer<Engine> engine_alloc() {
    return _engine_alloc();
  }

  late final _engine_allocPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<Engine> Function()>>(
          'engine_alloc');
  late final _engine_alloc =
      _engine_allocPtr.asFunction<ffi.Pointer<Engine> Function()>();

  Result engine_init(
    ffi.Pointer<Engine> self,
    int period_ms,
  ) {
    return Result.fromValue(_engine_init(
      self,
      period_ms,
    ));
  }

  late final _engine_initPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<Engine>, ffi.Uint32)>>('engine_init');
  late final _engine_init =
      _engine_initPtr.asFunction<int Function(ffi.Pointer<Engine>, int)>();

  void engine_uninit(
    ffi.Pointer<Engine> self,
  ) {
    return _engine_uninit(
      self,
    );
  }

  late final _engine_uninitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<Engine>)>>(
          'engine_uninit');
  late final _engine_uninit =
      _engine_uninitPtr.asFunction<void Function(ffi.Pointer<Engine>)>();

  Result engine_start(
    ffi.Pointer<Engine> self,
  ) {
    return Result.fromValue(_engine_start(
      self,
    ));
  }

  late final _engine_startPtr = _lookup<
          ffi.NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<Engine>)>>(
      'engine_start');
  late final _engine_start =
      _engine_startPtr.asFunction<int Function(ffi.Pointer<Engine>)>();

  Result engine_load_sound(
    ffi.Pointer<Engine> self,
    ffi.Pointer<Sound> sound,
    ffi.Pointer<ffi.Uint8> data,
    int data_size,
  ) {
    return Result.fromValue(_engine_load_sound(
      self,
      sound,
      data,
      data_size,
    ));
  }

  late final _engine_load_soundPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<Engine>, ffi.Pointer<Sound>,
              ffi.Pointer<ffi.Uint8>, ffi.Size)>>('engine_load_sound');
  late final _engine_load_sound = _engine_load_soundPtr.asFunction<
      int Function(ffi.Pointer<Engine>, ffi.Pointer<Sound>,
          ffi.Pointer<ffi.Uint8>, int)>();

  Result engine_generate_waveform(
    ffi.Pointer<Engine> self,
    ffi.Pointer<Sound> sound,
  ) {
    return Result.fromValue(_engine_generate_waveform(
      self,
      sound,
    ));
  }

  late final _engine_generate_waveformPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<Engine>,
              ffi.Pointer<Sound>)>>('engine_generate_waveform');
  late final _engine_generate_waveform = _engine_generate_waveformPtr
      .asFunction<int Function(ffi.Pointer<Engine>, ffi.Pointer<Sound>)>();

  Result engine_generate_noise(
    ffi.Pointer<Engine> self,
    ffi.Pointer<Sound> sound,
    NoiseType type,
  ) {
    return Result.fromValue(_engine_generate_noise(
      self,
      sound,
      type.value,
    ));
  }

  late final _engine_generate_noisePtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<Engine>, ffi.Pointer<Sound>,
              ffi.UnsignedInt)>>('engine_generate_noise');
  late final _engine_generate_noise = _engine_generate_noisePtr
      .asFunction<int Function(ffi.Pointer<Engine>, ffi.Pointer<Sound>, int)>();

  Result engine_generate_pulse(
    ffi.Pointer<Engine> self,
    ffi.Pointer<Sound> sound,
  ) {
    return Result.fromValue(_engine_generate_pulse(
      self,
      sound,
    ));
  }

  late final _engine_generate_pulsePtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<Engine>,
              ffi.Pointer<Sound>)>>('engine_generate_pulse');
  late final _engine_generate_pulse = _engine_generate_pulsePtr
      .asFunction<int Function(ffi.Pointer<Engine>, ffi.Pointer<Sound>)>();

  ffi.Pointer<Rec> rec_alloc() {
    return _rec_alloc();
  }

  late final _rec_allocPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<Rec> Function()>>('rec_alloc');
  late final _rec_alloc =
      _rec_allocPtr.asFunction<ffi.Pointer<Rec> Function()>();

  Result rec_init(
    ffi.Pointer<Rec> self,
    RecSink rec_sink,
    ffi.Pointer<ma_device> device,
  ) {
    return Result.fromValue(_rec_init(
      self,
      rec_sink,
      device,
    ));
  }

  late final _rec_initPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<Rec>, RecSink, ffi.Pointer<ma_device>)>>('rec_init');
  late final _rec_init = _rec_initPtr.asFunction<
      int Function(ffi.Pointer<Rec>, RecSink, ffi.Pointer<ma_device>)>();

  void rec_uninit(
    ffi.Pointer<Rec> self,
  ) {
    return _rec_uninit(
      self,
    );
  }

  late final _rec_uninitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<Rec>)>>(
          'rec_uninit');
  late final _rec_uninit =
      _rec_uninitPtr.asFunction<void Function(ffi.Pointer<Rec>)>();

  Result rec_write_raw(
    ffi.Pointer<Rec> self,
    ffi.Pointer<ffi.Uint8> data,
    int data_len_frames,
  ) {
    return Result.fromValue(_rec_write_raw(
      self,
      data,
      data_len_frames,
    ));
  }

  late final _rec_write_rawPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<Rec>, ffi.Pointer<ffi.Uint8>,
              ffi.Size)>>('rec_write_raw');
  late final _rec_write_raw = _rec_write_rawPtr.asFunction<
      int Function(ffi.Pointer<Rec>, ffi.Pointer<ffi.Uint8>, int)>();

  Result rec_end(
    ffi.Pointer<Rec> self,
  ) {
    return Result.fromValue(_rec_end(
      self,
    ));
  }

  late final _rec_endPtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<Rec>)>>(
          'rec_end');
  late final _rec_end =
      _rec_endPtr.asFunction<int Function(ffi.Pointer<Rec>)>();

  ffi.Pointer<Recorder> recorder_alloc(
    int max_rec_count,
  ) {
    return _recorder_alloc(
      max_rec_count,
    );
  }

  late final _recorder_allocPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<Recorder> Function(ffi.Size)>>(
          'recorder_alloc');
  late final _recorder_alloc =
      _recorder_allocPtr.asFunction<ffi.Pointer<Recorder> Function(int)>();

  Result recorder_init(
    ffi.Pointer<Recorder> self,
    int period_ms,
  ) {
    return Result.fromValue(_recorder_init(
      self,
      period_ms,
    ));
  }

  late final _recorder_initPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<Recorder>, ffi.Uint32)>>('recorder_init');
  late final _recorder_init =
      _recorder_initPtr.asFunction<int Function(ffi.Pointer<Recorder>, int)>();

  void recorder_uninit(
    ffi.Pointer<Recorder> self,
  ) {
    return _recorder_uninit(
      self,
    );
  }

  late final _recorder_uninitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<Recorder>)>>(
          'recorder_uninit');
  late final _recorder_uninit =
      _recorder_uninitPtr.asFunction<void Function(ffi.Pointer<Recorder>)>();

  bool recorder_get_is_recording(
    ffi.Pointer<Recorder> self,
    ffi.Pointer<Rec> rec,
  ) {
    return _recorder_get_is_recording(
      self,
      rec,
    );
  }

  late final _recorder_get_is_recordingPtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(ffi.Pointer<Recorder>,
              ffi.Pointer<Rec>)>>('recorder_get_is_recording');
  late final _recorder_get_is_recording = _recorder_get_is_recordingPtr
      .asFunction<bool Function(ffi.Pointer<Recorder>, ffi.Pointer<Rec>)>();

  Result recorder_start(
    ffi.Pointer<Recorder> self,
  ) {
    return Result.fromValue(_recorder_start(
      self,
    ));
  }

  late final _recorder_startPtr = _lookup<
          ffi.NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<Recorder>)>>(
      'recorder_start');
  late final _recorder_start =
      _recorder_startPtr.asFunction<int Function(ffi.Pointer<Recorder>)>();

  Result recorder_save_rec(
    ffi.Pointer<Recorder> self,
    ffi.Pointer<Rec> rec,
    AudioEncoding encoding,
    SampleFormat sample_format,
    int channel_count,
    int sample_rate,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> data_ptr,
    ffi.Pointer<ffi.Size> data_size_ptr,
  ) {
    return Result.fromValue(_recorder_save_rec(
      self,
      rec,
      encoding.value,
      sample_format.value,
      channel_count,
      sample_rate,
      data_ptr,
      data_size_ptr,
    ));
  }

  late final _recorder_save_recPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<Recorder>,
              ffi.Pointer<Rec>,
              ffi.UnsignedInt,
              ffi.UnsignedInt,
              ffi.Uint32,
              ffi.Uint32,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
              ffi.Pointer<ffi.Size>)>>('recorder_save_rec');
  late final _recorder_save_rec = _recorder_save_recPtr.asFunction<
      int Function(ffi.Pointer<Recorder>, ffi.Pointer<Rec>, int, int, int, int,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>, ffi.Pointer<ffi.Size>)>();

  Result recorder_resume_rec(
    ffi.Pointer<Recorder> self,
    ffi.Pointer<Rec> rec,
  ) {
    return Result.fromValue(_recorder_resume_rec(
      self,
      rec,
    ));
  }

  late final _recorder_resume_recPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<Recorder>, ffi.Pointer<Rec>)>>('recorder_resume_rec');
  late final _recorder_resume_rec = _recorder_resume_recPtr
      .asFunction<int Function(ffi.Pointer<Recorder>, ffi.Pointer<Rec>)>();

  Result recorder_pause_rec(
    ffi.Pointer<Recorder> self,
    ffi.Pointer<Rec> rec,
  ) {
    return Result.fromValue(_recorder_pause_rec(
      self,
      rec,
    ));
  }

  late final _recorder_pause_recPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<Recorder>, ffi.Pointer<Rec>)>>('recorder_pause_rec');
  late final _recorder_pause_rec = _recorder_pause_recPtr
      .asFunction<int Function(ffi.Pointer<Recorder>, ffi.Pointer<Rec>)>();
}

enum SoundDataType {
  SOUND_DATA_TYPE_ENCODED(0),
  SOUND_DATA_TYPE_WAVEFORM(1),
  SOUND_DATA_TYPE_NOISE(2),
  SOUND_DATA_TYPE_PULSE(3);

  final int value;
  const SoundDataType(this.value);

  static SoundDataType fromValue(int value) => switch (value) {
        0 => SOUND_DATA_TYPE_ENCODED,
        1 => SOUND_DATA_TYPE_WAVEFORM,
        2 => SOUND_DATA_TYPE_NOISE,
        3 => SOUND_DATA_TYPE_PULSE,
        _ => throw ArgumentError('Unknown value for SoundDataType: $value'),
      };
}

final class PrivateSoundDataImpl extends ffi.Struct {
  @ffi.UnsignedInt()
  external int typeAsInt;

  SoundDataType get type => SoundDataType.fromValue(typeAsInt);

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(ffi.Pointer<SoundData>)>> get_ds;

  external ffi
      .Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<SoundData>)>>
      uninit;
}

final class SoundData extends ffi.Struct {
  external ffi.Pointer<PrivateSoundDataImpl> __vtbl;

  external ffi.Pointer<ffi.Void> _self;
}

final class EncodedSoundData extends ffi.Opaque {}

enum Result {
  Ok(0),
  UnknownErr(1),
  OutOfMemErr(2),
  RangeErr(3),
  HashCollisionErr(4),
  FileUnavailableErr(5),
  FileReadingErr(6),
  FileWritingErr(7),
  FormatErr(8),
  ArgErr(9),
  StateErr(10),
  RESULT_COUNT(11);

  final int value;
  const Result(this.value);

  static Result fromValue(int value) => switch (value) {
        0 => Ok,
        1 => UnknownErr,
        2 => OutOfMemErr,
        3 => RangeErr,
        4 => HashCollisionErr,
        5 => FileUnavailableErr,
        6 => FileReadingErr,
        7 => FileWritingErr,
        8 => FormatErr,
        9 => ArgErr,
        10 => StateErr,
        11 => RESULT_COUNT,
        _ => throw ArgumentError('Unknown value for Result: $value'),
      };
}

final class NoiseSoundData extends ffi.Opaque {}

enum NoiseType {
  NOISE_TYPE_WHITE(0),
  NOISE_TYPE_PINK(1),
  NOISE_TYPE_BROWNIAN(2);

  final int value;
  const NoiseType(this.value);

  static NoiseType fromValue(int value) => switch (value) {
        0 => NOISE_TYPE_WHITE,
        1 => NOISE_TYPE_PINK,
        2 => NOISE_TYPE_BROWNIAN,
        _ => throw ArgumentError('Unknown value for NoiseType: $value'),
      };
}

final class PulseSoundData extends ffi.Opaque {}

final class WaveformSoundData extends ffi.Opaque {}

enum WaveformType {
  WAVEFORM_TYPE_SINE(0),
  WAVEFORM_TYPE_SQUARE(1),
  WAVEFORM_TYPE_TRIANGLE(2),
  WAVEFORM_TYPE_SAWTOOTH(3);

  final int value;
  const WaveformType(this.value);

  static WaveformType fromValue(int value) => switch (value) {
        0 => WAVEFORM_TYPE_SINE,
        1 => WAVEFORM_TYPE_SQUARE,
        2 => WAVEFORM_TYPE_TRIANGLE,
        3 => WAVEFORM_TYPE_SAWTOOTH,
        _ => throw ArgumentError('Unknown value for WaveformType: $value'),
      };
}

final class Sound extends ffi.Opaque {}

final class ma_engine extends ffi.Opaque {}

final class Engine extends ffi.Opaque {}

enum RecSinkType {
  REC_SINK_TYPE_ENCODED(0);

  final int value;
  const RecSinkType(this.value);

  static RecSinkType fromValue(int value) => switch (value) {
        0 => REC_SINK_TYPE_ENCODED,
        _ => throw ArgumentError('Unknown value for RecSinkType: $value'),
      };
}

final class ma_encoder extends ffi.Opaque {}

final class PrivateRecSinkImpl extends ffi.Struct {
  @ffi.UnsignedInt()
  external int typeAsInt;

  RecSinkType get type => RecSinkType.fromValue(typeAsInt);

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Pointer<ma_encoder> Function(ffi.Pointer<RecSink>)>> get_enc;

  external ffi
      .Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<RecSink>)>>
      uninit;
}

final class RecSink extends ffi.Struct {
  external ffi.Pointer<PrivateRecSinkImpl> __vtbl;

  external ffi.Pointer<ffi.Void> _self;
}

final class Rec extends ffi.Opaque {}

final class ma_device extends ffi.Opaque {}

final class Recorder extends ffi.Opaque {}

typedef RecorderOnDataFn = ffi.NativeFunction<
    ffi.Void Function(
        ffi.Size pos, ffi.Pointer<ffi.Uint8> data, ffi.Size data_size)>;

enum AudioEncoding {
  AUDIO_ENCODING_RAW(0),
  AUDIO_ENCODING_WAV(1),
  AUDIO_ENCODING_FLAC(2),
  AUDIO_ENCODING_MP3(3);

  final int value;
  const AudioEncoding(this.value);

  static AudioEncoding fromValue(int value) => switch (value) {
        0 => AUDIO_ENCODING_RAW,
        1 => AUDIO_ENCODING_WAV,
        2 => AUDIO_ENCODING_FLAC,
        3 => AUDIO_ENCODING_MP3,
        _ => throw ArgumentError('Unknown value for AudioEncoding: $value'),
      };
}

enum SampleFormat {
  SAMPLE_FORMAT_U8(1),
  SAMPLE_FORMAT_S16(2),
  SAMPLE_FORMAT_S24(3),
  SAMPLE_FORMAT_S32(4),
  SAMPLE_FORMAT_F32(5);

  final int value;
  const SampleFormat(this.value);

  static SampleFormat fromValue(int value) => switch (value) {
        1 => SAMPLE_FORMAT_U8,
        2 => SAMPLE_FORMAT_S16,
        3 => SAMPLE_FORMAT_S24,
        4 => SAMPLE_FORMAT_S32,
        5 => SAMPLE_FORMAT_F32,
        _ => throw ArgumentError('Unknown value for SampleFormat: $value'),
      };
}
