publish_to: none
name: minisound_platform_interface
description: A common platform interface for the Minisound package.
version: 1.5.0
repository: https://github.com/DaniilAlpha/minisound/tree/master/minisound_platform_interface

#####

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_lints: ^2.0.1
