name: example
description: Demonstrates how to use the Minisound package.
version: 1.0.0
publish_to: none

#####

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  minisound:
    path: ../
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

#####

flutter:
  uses-material-design: true

  assets:
    - assets/
